
import './globals.css'
import {  Alegreya } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const alegreya = Alegreya({ subsets: ['latin'] });

export const metadata = {
  title: 'Question Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={alegreya.className}>{children}</body>
    </html>
  )
}
